### ISSUE TITLE
Crosshairs disappear after first shot of clip in blasters

### ISSUE THREAD

**Issue by Servius** [Servius/sepcrisistroopsgui#11]
Crosshairs disappear after first shot of clip in blasters
https://github.com/Servius/sepcrisistroopsgui/blob/4b32d3a7ebc6e59e4ee320db160c9aad6b8f93f1/SeparatistCrisis/ModuleData/weapons_blaster.xml#L370

**Comment by AJannik** [comment]
Resolved
