### ISSUE TITLE
Encyclopedia Bug/Crash

### ISSUE THREAD

**Issue by Servius** [Servius/sepcrisistroopsgui#12]
Encyclopedia Bug/Crash

**Comment by AJannik** [comment]
Count Dooku is broken which is causing the ctd when opening Encyclopedia
Or more accurately it looks like the clans and faction of Count Dooku are the problem.
"allAliveHero.Clan?.Name.ToString() ?? "")" the .Name is returning null so something about the clan name is wack

**Comment by AJannik** [comment]
Some heros are not assigned the correct clans atm. For example Jango Fett is not setup correctly causing to crash when opening his Encyclopedia page
