### ISSUE TITLE
module_strings.xml doesnt load/do anything despite being setup?

### ISSUE THREAD

**Issue by Servius** [Servius/sepcrisistroopsgui#13]
module_strings.xml doesnt load/do anything despite being setup?
https://github.com/Servius/sepcrisistroopsgui/blob/a522aa289ab749ee73fb6166b9d618fcdd9f6a64/SeparatistCrisis/ModuleData/module_strings.xml#L6

**Comment by Servius** [comment]
![image](https://user-images.githubusercontent.com/16316223/148529602-0924b03c-0632-4fb2-8f4d-3916bcd709ea.png)

**Comment by AJannik** [comment]
Resolved
