### ISSUE TITLE
Crash when sieging a city ; On initialization

### ISSUE THREAD

**Issue by Servius** [Servius/sepcrisistroopsgui#19]
Crash when sieging a city ; On initialization reported by Arctic Freeze

**Comment by ArcticFreeze99** [comment]
[rgl_log_16368.txt](https://github.com/Servius/sepcrisistroopsgui/files/7860678/rgl_log_16368.txt)
[rgl_log_errors_16368.txt](https://github.com/Servius/sepcrisistroopsgui/files/7860679/rgl_log_errors_16368.txt)

**Comment by AJannik** [comment]
@ArcticFreeze99 Can you give me some more details on how to trigger the crash so I can recreate it on my end

**Comment by ArcticFreeze99** [comment]
@AJannik Crash happens when Besieging Chaikand Settlement, under Khuzait Ownership
Happens when clicking the initial button to besiege the settlement

**Comment by AJannik** [comment]
![error](https://user-images.githubusercontent.com/67471557/149508430-e5062600-5780-4ea4-a363-aafed4a91831.PNG)
Seems to be a map problem. Its trying to load more siege weapons then the town can support

**Comment by AJannik** [comment]
Can confirm: Our main_map is outdated and causing this crash

**Comment by AJannik** [comment]
Will be resolved in #20
