### ISSUE TITLE
Define Culture start locations

### ISSUE THREAD

**Issue by Servius** [Servius/sepcrisistroopsgui#21]
Define Culture start locations

Its a non-xml thing
SandboxCharacterCreationContent

**Comment by Servius** [comment]
![image](https://user-images.githubusercontent.com/16316223/149679878-c5a23fde-4ad9-4f1c-8ad0-c89d281fff1d.png)
@AJannik was sent how to automate the culture locations by gnivler

**Comment by AJannik** [comment]
Resolved
