### ISSUE TITLE
E5 Blaster is broken

### ISSUE THREAD

**Issue by AJannik** [Servius/sepcrisistroopsgui#34]
Game crashes when the E5 Blaster (used by Nimbus Commando) is used in Battle. It already crashes when you move an unit that has the E5 equipped (like giving movement order or just nugging the unit with the player character)

Problem seems to be an import or setup problem?
![err](https://user-images.githubusercontent.com/67471557/152826747-54b58f9e-9b14-4a5a-adc3-fccac315cff9.PNG)

**Comment by Servius** [comment]
Fixed! Also updated the model using tbros refreshed asset
