### ISSUE TITLE
Retain atmosphere presets for specific maps

### ISSUE THREAD

**Issue by Servius** [Servius/sepcrisistroopsgui#35]
![image](https://user-images.githubusercontent.com/16316223/155393280-6321a39a-13c2-448d-8848-64e7dcd3f7df.png)
![image](https://user-images.githubusercontent.com/16316223/155393338-80c9feaa-981f-4cb8-9679-9a70e6088bb8.png)

Mappers need a way to set a custom atmosphere preset for maps and have it be kept/used when playing on our levels. 

Could be something that overrides the atmospheres based on whats listed in an .xml 
_scenename=geonosisbattelmap_01a , atmosphere override = geonosis_atmosphere_

**Comment by Servius** [comment]
Reached out to hunharibo to see if he will provide us with his code or insights on how to accomplish this task. 

![image](https://user-images.githubusercontent.com/16316223/155404479-8fbbd7af-c911-4215-8ff4-b1758de502bb.png)

**Comment by Servius** [comment]
@AJannik Solution provided! 🥇 

![image](https://user-images.githubusercontent.com/16316223/155405857-cec133f9-dfc3-4060-8c49-b8dff9fbd0df.png)
![image](https://user-images.githubusercontent.com/16316223/155405904-5bfcf8f2-c9bd-4303-9919-17d74063ae11.png)
![image](https://user-images.githubusercontent.com/16316223/155405937-3df23263-2d11-458d-bdcf-5fcb22b72e56.png)

**Comment by AJannik** [comment]
Resolved
